<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

### <font color="green">1.1 Challenge: Importing our Library</font>

In [2]:
# Let's import numpy
#
import numpy as np

### <font color="green">1.2 Challenge: Creating an Array</font>

In [ ]:
# Challenge 1 
# Create an array of five zeros
#
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
# Challenge 2
# Create an array of six ones 
#
arr1 = np.ones(6)
print(arr1)

[1. 1. 1. 1. 1. 1.]


In [ ]:
# Challenge 3
# Create an array of the integers from 10 to 50
#
arr2 = np.arange(10, 50)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Challenge 4
# Create an array of odd integers from 20 to 60
#
arr3 = np.arange(20, 60)
print(arr3)
i = []
for element in arr3:
    if element %2 == 0:
        i.append(True)
    else:
        i.append(False)
print(i)
print(arr3[i])

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
[True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]


In [16]:
arr = [40, 41, 42, 43, 44, 45]
x = []
for n in arr:
    if n > 43:
        x.append(True)
    else:
        x.append(False)

print(x)


[False, False, False, False, True, True]


In [ ]:
# Challenge 5
# Create an array of 25 random numbers 
#
arr4 = np.random.rand(25)
print(arr4)
arr5 = np.random.randint(0, 100, 25)
print(arr5)

[0.23468069 0.59835942 0.31835469 0.88907731 0.66740711 0.52904472
 0.80010133 0.56476552 0.49429056 0.92324867 0.26812704 0.4070269
 0.81261955 0.34773802 0.4880698  0.84576953 0.81721929 0.90221082
 0.43447504 0.31086059 0.17307536 0.25950231 0.76161924 0.99377514
 0.54727479]
[83 21 77 52 43 55 42 99 27 53 84 66 10 51 47 35 79  0 15 45 83 13 50 44
  1]


### <font color="green">1.3 Working with Matrices</font>

In [ ]:
# Challenge 6
# Write code to replicate the expected matrix output 
# of the cell shown below
# 
x = np.arange(1, 21)
print(x.reshape(5, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
# Challenge 6: Expected Output
# [Do not run this cell]
# The output of this cell will disappear when run

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
# Challenge 7
# Let's write code to replicate the expected matrix output 
# of the cell shown below
# 

x1 = x.reshape(5, 4)
print(x1)
new_arr = x1[3:, 1:]
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[14 15 16]
 [18 19 20]]


In [ ]:
# Challenge 7: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

[[14 15 16]
 [18 19 20]]


In [ ]:
# Challenge 8
# Let's write code to replicate the expected matrix output 
# of the cell shown below
# 
print(x1[4, 3])

20


In [ ]:
# Challenge 8: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

20

In [ ]:
# Challenge 9
# Let's write code to replicate the expected matrix output 
# of the cell shown below
#
print(x1[3:, 0:])

[[13 14 15 16]
 [17 18 19 20]]


In [ ]:
# Challenge 9: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

[[13 14 15 16]
 [17 18 19 20]]


In [ ]:
# Challenge 10
# Let's find out the mean of first column values 
# in our matrix in challenge 6 above
# 
avarage = np.mean(x1[0:, 0])
print(avarage)

9.0


In [ ]:
# Challenge 11
# Let's find out the sum of second column values 
# in our matrix in challenge 6 above
#
sumation = np.sum(x1[0:, 1])
print(sumation)

50


In [ ]:
# Challenge 12
# How do we find out the sum of all columns of the challenge 6 output
# The resulting array should contain the sums of each column
# 
total = np.sum(x1)
print(total)

210
